# Generated by Django 4.1.1 on 2022-09-21 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Familiar',
            fields=[
                ('id_familiar', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=45, verbose_name='Nombre completo')),
                ('telefono', models.CharField(max_length=25, verbose_name='numero celular')),
                ('correo', models.CharField(max_length=40, verbose_name='correo')),
                ('direccion', models.CharField(max_length=45, verbose_name='direccion')),
                ('ciudad', models.CharField(max_length=25, verbose_name='Ciudad')),
            ],
        ),
    ]
