# Generated by Django 4.1.1 on 2022-09-22 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0002_familiar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id_paciente', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=45, verbose_name='nombres')),
                ('apellidos', models.CharField(blank=True, max_length=45, null=True, verbose_name='apellidos')),
                ('genero', models.CharField(default='Some String', max_length=45, verbose_name='genero')),
                ('tipo_documento', models.CharField(blank=True, max_length=45, null=True, verbose_name='tipo_documento')),
                ('numero_documento', models.CharField(max_length=45, verbose_name='numero_documento')),
                ('email', models.EmailField(max_length=45, verbose_name='email')),
                ('telefono', models.CharField(max_length=45, verbose_name='telefono')),
                ('direccion', models.CharField(max_length=45, verbose_name='direccion')),
                ('ciudad', models.CharField(default='Some String', max_length=45, verbose_name='ciudad')),
            ],
        ),
        migrations.DeleteModel(
            name='Familiar',
        ),
        migrations.DeleteModel(
            name='Pacientes',
        ),
    ]
