# Generated by Django 4.1.1 on 2022-09-22 00:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0003_paciente_delete_familiar_delete_pacientes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='numero_documento',
            field=models.CharField(max_length=45, verbose_name='numero de documento'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='tipo_documento',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='tipo de documento'),
        ),
        migrations.CreateModel(
            name='Historia_clinica',
            fields=[
                ('id_historia', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_registro', models.DateField(auto_now_add=True, verbose_name='fecha_registro')),
                ('fecha_consulta', models.DateField()),
                ('recomenacion_medica', models.TextField()),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historia_clinica', to='aplicacion.paciente')),
            ],
        ),
    ]
