# Generated by Django 4.1.1 on 2022-09-22 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0004_alter_paciente_numero_documento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personal_medico',
            fields=[
                ('id_medico', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=45, verbose_name='nombres')),
                ('apellidos', models.CharField(blank=True, max_length=45, null=True, verbose_name='apellidos')),
                ('genero', models.CharField(max_length=45, verbose_name='genero')),
                ('tipo_documento', models.CharField(blank=True, max_length=45, null=True, verbose_name='tipo_documento')),
                ('numero_documento', models.CharField(max_length=45, verbose_name='numero_documento')),
                ('email', models.EmailField(max_length=45, verbose_name='email')),
                ('telefono', models.CharField(max_length=45, verbose_name='telefono')),
                ('area_desempeño', models.CharField(max_length=45, verbose_name='area_desempeño')),
                ('especialidad', models.CharField(max_length=45, verbose_name='especialidad')),
            ],
        ),
    ]
