# Generated by Django 4.1.1 on 2022-09-22 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0005_personal_medico'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signos_vitales',
            fields=[
                ('id_signos_vitales', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_registro', models.DateField(auto_now_add=True, verbose_name='fecha_registro')),
                ('oximetria', models.CharField(max_length=45, verbose_name='oximetria')),
                ('frecuencia_respiratoria', models.CharField(max_length=45, verbose_name='frecuencia_respiratoria')),
                ('temperatura', models.CharField(max_length=45, verbose_name='temperatura')),
                ('presion_arterial', models.CharField(max_length=45, verbose_name='presion_arterial')),
                ('glicemias', models.CharField(max_length=45, verbose_name='glicemias')),
                ('id_paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signos_vitales', to='aplicacion.paciente')),
            ],
        ),
    ]
