# Generated by Django 4.1.1 on 2022-09-22 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0006_signos_vitales'),
    ]

    operations = [
        migrations.CreateModel(
            name='Familiar',
            fields=[
                ('id_Familiar', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=45, verbose_name='nombres')),
                ('apellidos', models.CharField(blank=True, max_length=45, null=True, verbose_name='apellidos')),
                ('tipo_documento', models.CharField(blank=True, max_length=45, null=True, verbose_name='tipo de documento')),
                ('numero_documento', models.CharField(max_length=45, verbose_name='numero de documento')),
                ('genero', models.CharField(default='Some String', max_length=45, verbose_name='genero')),
                ('parentesco', models.CharField(max_length=45, verbose_name='parentesco')),
                ('email', models.EmailField(max_length=45, verbose_name='email')),
                ('telefono', models.CharField(max_length=45, verbose_name='telefono')),
                ('direccion', models.CharField(max_length=45, verbose_name='direccion')),
            ],
        ),
        migrations.AlterField(
            model_name='personal_medico',
            name='area_desempeño',
            field=models.CharField(max_length=45, verbose_name='area desempeño'),
        ),
        migrations.AlterField(
            model_name='personal_medico',
            name='numero_documento',
            field=models.CharField(max_length=45, verbose_name='numero de documento'),
        ),
        migrations.AlterField(
            model_name='personal_medico',
            name='tipo_documento',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='tip de documento'),
        ),
        migrations.AlterField(
            model_name='signos_vitales',
            name='frecuencia_respiratoria',
            field=models.CharField(max_length=45, verbose_name='frecuencia respiratoria'),
        ),
        migrations.AlterField(
            model_name='signos_vitales',
            name='presion_arterial',
            field=models.CharField(max_length=45, verbose_name='presion arterial'),
        ),
    ]
